(specifications->manifest
  '(
    "breeze"
    "calibre"
    "cairo" ;; conky
    "conky"
    "desktop-file-utils" ;; xdg capture firefox/emacsclient
    "dunst"
    "gimp"
    "jonaburg-picom"
    "krita"
    "light"
    "lua" ;; conky
    "lua-lgi" ;; conky
    "lxqt-panel"
    "lxqt-qtplugin"
    "lxrandr"
    "pulseaudio" ;; for pactl
    "mesa-utils"
    "mpv"
    "oxygen-icons"
    "qlipper"
    "qtbase"
    "qtsvg"
    "redshift"
    "rofi"
    "rxvt-unicode"
    "setxkbmap"
    "transmission"
    "unclutter"
    "vlc"
    "w7-st"
    "wireshark"
    "wmctrl"
    "xbindkeys"
    "xclip"
    "xdotool"
    "xev"
    "xeyes"
    "xinput"
    "xmodmap"
    "xournal"
    "xprop"
    "xrandr"
    "xscreensaver"
    "xset"
    "zathura"
    "zathura-ps"
    "zathura-pdf-mupdf"
    ))
