(specifications->manifest
  '(
    "bc"
    "bmon"
    "btrfs-progs"
    "cowsay"
    "bash"
    "cryptsetup" ;; add fs tools
    "dash"
    "darcs"
    "emacs"
    "emacs-guix"
    "exa"
    "fd"
    "feh"
    "file"
    "fortune-mod"
    "hunspell"
    "hunspell-dict-fr-toutesvariantes"
    "hunspell-dict-en-us"
    "hunspell-dict-en-gb"
    "hunspell-dict-en-gb-ize"
    "git"
    "gnupg"
    "imagemagick"
    "jq"
    "util-linux"
    "mksh"
    "mtr"
    "neofetch"
    "mercurial"
    "ncurses" ;; clear! tic (terminfo)
    "nmap"
    "onionshare"
    "pandoc"
    "password-store"
    "pavucontrol-qt"
    "pinentry"
    "pinentry-qt"
    "pinentry-tty"
    "plantuml"
    "recutils"
    "ripgrep"
    "rsync"
    "s6"
    "s6-rc"
    "skim"
    "sloccount"
    "sqlite"
    "strace"
    "tig"
    "time"
    "tmux"
    "tmux-xpanes"
    "torsocks"
    "tree"
    "unison"
    "unrar"
    "unrtf"
    "unzip"
    "valgrind"
    "vim-full"
    "w3m"
    "weechat"
    "xdg-user-dirs"
    "xdg-utils"
    "youtube-dl"
    "zsh"
    "pinentry" "pinentry-qt" "pinentry-tty"
    ;; "x2x" FIXME add this
    ;; net
    "iwd"
    "bind:utils"
    "wireguard-tools" ;;
    "openresolv" ;; network stuff in a separate file?
    "isc-dhcp"
    "tcpdump"
    "wget"
    "curl"
    "socat"
    "netcat-openbsd"
    "nftables"
    "inetutils" ;; hostname, telnet, ftp
    "iftop"
    ))
